name: Publish

on:
  push:
    tags:
      - 'v*'

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install build backend
        run: |
          python -m pip install --upgrade pip
          pip install build
      - name: Build sdist and wheel
        run: python -m build
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/

  publish-testpypi:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist
      - name: Publish to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/

  smoke-test:
    needs: publish-testpypi
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install from TestPyPI
        run: |
          python -m pip install --upgrade pip
          pip install -i https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple timewarp-llm
      - name: Smoke import and CLI
        run: |
          python - <<'PY'
          import timewarp
          print('all:', len(getattr(timewarp, '__all__', [])))
          PY
          timewarp --help || true

  publish-pypi:
    if: ${{ !contains(github.ref_name, 'rc') }}
    needs: [build, smoke-test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1

